variable "aws_public_subnet" {}
variable "cluster_name" {}
variable "public_access_cidrs" {}
variable "node_group_name" {}
variable "scaling_desired_size" {}
variable "scaling_max_size" {}
variable "scaling_min_size" {}
variable "instance_types" {}
variable "key_pair" {}
variable "role_arn" {}
variable "nodeSGid" {}
variable "rolearn2" {}
variable "nodegroupID" {}
variable "clusterpolicy" {}
variable "controller" {}
variable "nodepolicy" {}
variable "cnipolicy" {}
variable "registry" {}